### ISSUE TITLE
post to getlektor.com

### ISSUE THREAD

**Issue by nixjdm** [a2csuga/lektor-root-relative-path#2]
Hey @a2csuga! I'm Lektor's maintainer, and I found your plugin. I want to encourage you to open a pull request to https://github.com/lektor/lektor-website to add it to the list of available plugins. You can read about how to do that here: https://www.getlektor.com/docs/plugins/publishing/

I hope you do!

Thanks!

**Comment by a2csuga** [comment]
Hi nixjdm,
Sorry for replying very late. I made the pull request.
https://github.com/lektor/lektor-website/pull/252

Thank you for interested in my plugin. 

Thanks

**Comment by a2csuga** [comment]
Thank you for accepting my pull request. Issue closed.

Thanks
